export default {
    settings: { logo: ''},
    slides: [],
    clients: [],
    offers: [],
    phones: [],
    emails: [],
    services: [],
    socialMedia: [],
    images: [],
    categories: [],
    products: [],
    cart: [],
    isLoading: false,
};
